library(data.table)
library(dplyr)
library(here)
library(httr)
library(lubridate)
library(purrr)
library(RAQSAPI)
library(readr)
library(slider)
library(tidyr)
library(writexl)
library(zoo)

here()

source(here("update_all_data.R"))
source(here("process_all_data.R"))